import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HomeSearch from '@/app/ui/homeSearch'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'EEBAY or something',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
          
          <body className={inter.className}>
              <div className="fixed top-0 left-0 right-0 flex justify-between items-center h-16 bg-blue-900 text-white px-8">
              <p className="font-mono text-sm">
                  Welcome to DRM Name TBD
              </p>
              <div className="flex justify-center items-center">
                  <HomeSearch placeholder="Search cards..." />
              </div>
              <div className="flex items-center">
                  <div className="mr-4">Home</div>
                  <div className="mr-4">Profile</div>
                  <div className="mr-4">Settings</div>

              </div>
          </div>
              {children}
          </body>
    </html>
  )
}
