import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HomeSearch from '@/app/ui/homeSearch'
import Image from 'next/image';
import logo from '@/public/logo.png';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'EEBAY or something',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
          
          <body className={inter.className}>
              
              <div className="fixed top-0 left-0 right-0 flex justify-between items-center h-16 bg-blue-900 text-white px-8 z-30">
                  <Image src={logo} alt="logo" className="w-16 h-16" />
                  <p className="font-mono text-sm">
                      Welcome to DRM Name TBD
                  </p>

                  <div className="flex items-center">
                      <a href="/" className="mr-4">
                          Home
                      </a>
                      <a href="/cardlist" className="mr-4">
                          Cards
                      </a>
                      <a href="/createlisting" className="mr-4">
                          New Listing
                      </a>
                  </div>
              </div>
              {children}
          </body>
    </html>
  )
}
